# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to render
        run:  bash ${GITHUB_WORKSPACE}/.github/deploy.sh
        
  
  runTests:
    needs: [deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: vaidkaran/effortless_test_runner
          ref: 'main'
          token: ${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}
      - name: Install dependencies
        env:
          EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN: ${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: Run tests
        run: npm run test:qa
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: Download test reports
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: ${GITHUB_WORKSPACE}/mochawesome-report/**/*
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          #pattern: # optional
          # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          #merge-multiple: # optional, default is false
          # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          #github-token: # optional
          # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          #repository: # optional, default is ${{ github.repository }}
          # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          #run-id: # optional, default is ${{ github.run_id }}
        
          
