# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to render
        run:  bash ${GITHUB_WORKSPACE}/.github/deploy.sh
  
  runTests:
    needs: [build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
      
    steps:
      - uses: actions/checkout@v4
        with:
          repository: vaidkaran/effortless_test_runner
          ref: 'main'
          token: ${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}
      - name: Install dependencies
        env:
          EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN: ${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.EFFORTLESS_TEST_RUNNER_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: Run tests
        run: npm run test:prod
